title: "Stef"
description: "Portfolio"
remote_theme: tedivm/jekyll-theme-portfolio

plugins:
  - jekyll-remote-theme
  - jekyll-feed

email: sxs551@psu.edu
github_username: sxs551

nav:
  - title: About
    url: /about
