remote_theme: sproogen/modern-resume-theme

plugins:
  - jekyll-remote-theme

title: "Your Name"
name: "Your Name"
email: "you@example.com"
website: "https://YOURUSERNAME.github.io/YOURREPO"
github_username: "YOURUSERNAME"
linkedin_username: "YOUR-LINKEDIN-SLUG"

darkmode: true
